// Category icons
export { default as IC_CAT_FOOD }          from './assets/icons/cat_food.svg'
export { default as IC_CAT_GROCERY }       from './assets/icons/cat_grocery.svg'
export { default as IC_CAT_TRANSPORT }     from './assets/icons/cat_transport.svg'
export { default as IC_CAT_HOME }          from './assets/icons/cat_home.svg'
export { default as IC_CAT_CLOTHING }      from './assets/icons/cat_clothing.svg'
export { default as IC_CAT_ENTERTAINMENT } from './assets/icons/cat_entertainment.svg'
export { default as IC_CAT_SHOPPING }      from './assets/icons/cat_shopping.svg'
export { default as IC_CAT_OTHER }         from './assets/icons/cat_other.svg'
export { default as IC_CAT_UTILITIES }     from './assets/icons/cat_utilities.svg'

// UI icons
export { default as IC_TYPE_ADD }      from './assets/icons/ic_type_add.svg'
export { default as IC_TYPE_TRN }      from './assets/icons/ic_type_trn.svg'
export { default as IC_TYPE_INC }      from './assets/icons/ic_type_inc.svg'
export { default as IC_MORE }          from './assets/icons/ic_more.svg'
export { default as IC_CALENDAR }      from './assets/icons/ic_calendar.svg'
export { default as IC_DOTS }          from './assets/icons/ic_dots.svg'
export { default as IC_CARD }          from './assets/icons/ic_card.svg'
export { default as IC_CHEVRON }       from './assets/icons/ic_chevron.svg'
export { default as IC_DELETE }        from './assets/icons/ic_delete.svg'
export { default as IC_TAB_HOME }      from './assets/icons/ic_tab_home.svg'
export { default as IC_TAB_ASSISTANT } from './assets/icons/ic_tab_assistant.svg'
export { default as IC_TAB_BUDGET }    from './assets/icons/ic_tab_budget.svg'
export { default as IC_TAB_ANALYTICS } from './assets/icons/ic_tab_analytics.svg'
export { default as IC_FAB_PLUS }      from './assets/icons/ic_fab_plus.svg'
export { default as IC_PROFILE }       from './assets/icons/ic_profile.svg'
export { default as IC_SETTINGS }      from './assets/icons/ic_settings.svg'
